#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("i1", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("i2", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("i3", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("i4", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("i5", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("i6", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("o1", 32, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("o1_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("o2", 32, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("o2_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("o3", 32, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("o3_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("o4", 32, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("o4_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("G1", 32, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("G2", 32, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("G3", 32, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("G4", 32, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("GG1", 32, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("GG2", 32, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("ap_return1", 32, hls_out, 16, "ap_vld", "out_data", 1),
	Port_Property("ap_return1_ap_vld", 1, hls_out, 16, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "hls_macc";
