#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("in1", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("in2", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("in3", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("in4", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("in5", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("in6", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("in7", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("in8", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("in9", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("in10", 32, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("out1", 32, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("out1_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("out2", 32, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("out2_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
	Port_Property("out3", 32, hls_out, 12, "ap_vld", "out_data", 1),
	Port_Property("out3_ap_vld", 1, hls_out, 12, "ap_vld", "out_vld", 1),
	Port_Property("ap_return", 32, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "hls_macc";
