#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("in1", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("in2", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("in3", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("in4", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("in7", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("in8", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("in9", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("in10", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("in14", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("in12", 32, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("in15", 32, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("in17", 32, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("in19", 32, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("in20", 32, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("in22", 32, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("in24", 32, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("in27", 32, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("in28", 32, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("in29", 32, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("in32", 32, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("out13", 32, hls_out, 20, "ap_vld", "out_data", 1),
	Port_Property("out13_ap_vld", 1, hls_out, 20, "ap_vld", "out_vld", 1),
	Port_Property("out30_i", 32, hls_in, 21, "ap_ovld", "in_data", 1),
	Port_Property("out30_o", 32, hls_out, 21, "ap_ovld", "out_data", 1),
	Port_Property("out30_o_ap_vld", 1, hls_out, 21, "ap_ovld", "out_vld", 1),
	Port_Property("out31", 32, hls_out, 22, "ap_vld", "out_data", 1),
	Port_Property("out31_ap_vld", 1, hls_out, 22, "ap_vld", "out_vld", 1),
	Port_Property("ap_return", 32, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "hls_macc";
